spring:
  output.ansi.enabled: DETECT
  session.store-type: none

server:
  compression.enabled: true

# URI is of the form mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
spring.data.mongodb.uri: mongodb://localhost/dcexporter

application:
  url: http://localhost:3000
  security:
    fetchUserInfo: true
  syncDelay: 10000

# TODO : Copied pasted from portal configuration, check if we really need all of them
kernel:
  base_uri: https://kernel.ozwillo-preprod.eu
  alt_uri: ${kernel.base_uri}
  auth:
    issuer: ${kernel.base_uri}/
    auth_endpoint: ${kernel.alt_uri}/a/auth
    token_endpoint: ${kernel.base_uri}/a/token
    keys_endpoint: ${kernel.base_uri}/a/keys
    userinfo_endpoint: ${kernel.base_uri}/a/userinfo
    profile_endpoint: ${kernel.base_uri}/d/user
    password_change_endpoint: ${kernel.alt_uri}/a/password
    revoke_endpoint: ${kernel.base_uri}/a/revoke
    logout_endpoint: ${kernel.alt_uri}/a/logout
    callback_uri: ${application.url}/callback
    home_uri: ${application.url}
  user_directory_endpoint: ${kernel.base_uri}/d
  event_bus_endpoint: ${kernel.base_uri}/e
  notifications_endpoint: ${kernel.base_uri}/n
  client_id: portal
  scopes_to_require: openid profile email datacore

datacore:
  url: https://data.ozwillo-preprod.eu
  containerUrl: http://data.ozwillo.com
  systemAdminUser:  # Get it using Node.js lib / with portal clientId
    nonce: 970774665428326      #Set it when getting the refreshToken
  exportExcludedFields:
    # General rule
    - "@type"
    # For organizations
    - relt:displayName
    - adrpost:adminUnit
    - orgpu:officialId
    - orgtypch:idStat2
    - orgtypch:mayor
    - orgtypch:mayorTitle
    - org:altName
    - org:displayAltName
    - org:country
    - org:vatNumber
    - org:source
    # For POIs
    - org:email
    - poi:author
    # For electoral roll registration (CK)
    - ck_electoral_roll_registration:nom_de_famille
    - ck_electoral_roll_registration:nom_d_usage
    - ck_electoral_roll_registration:prenom
    - ck_electoral_roll_registration:adresse1
    - ck_electoral_roll_registration:adresse2
    - ck_electoral_roll_registration:courriel
    - ck_electoral_roll_registration:telephone
    - ck_electoral_roll_registration:justificatif_identite
    - ck_electoral_roll_registration:justificatifs_domicile
    - ck_electoral_roll_registration:commune_origine
    - ck_electoral_roll_registration:code_departement_origine
    - ck_electoral_roll_registration:libelle_territoire_outremer_origine
    - ck_electoral_roll_registration:ambassade_poste_consulaire_origine
    - ck_electoral_roll_registration:pays_origine
    - ck_electoral_roll_registration:date_de_naissance
    - ck_electoral_roll_registration:commune_de_naissance
    - ck_electoral_roll_registration:code_departement_de_naissance
    - ck_electoral_roll_registration:libelle_territoire_de_naissance_outremer
    - ck_electoral_roll_registration:pays_de_naissance
  modifiedField: "dc:modified"

ckan:
  url: https://opendata-preprod.data-ozwillo.org
